default: demo-maas
environments:
    # https://juju.ubuntu.com/docs/config-maas.html
    maas:
        type: maas

        # maas-server specifies the location of the MAAS server. It must
        # specify the base path.
        #
        maas-server: 'http://10.4.1.1/MAAS/'

        # maas-oauth holds the OAuth credentials from MAAS.
        #
        maas-oauth: 'c6tcQz4tyS3ALajCtF:sqcWhw8MkxTjUDLZrm:hBhszBLv5EqrY8h6yktFXWUT5825ShvE'

        # maas-server bootstrap ssh connection options
        #

        # bootstrap-timeout time to wait contacting a state server, in seconds.
        bootstrap-timeout: 1800
        admin-secret: admin

        # Whether or not to refresh the list of available updates for an
        # OS. The default option of true is recommended for use in
        # production systems, but disabling this can speed up local
        # deployments for development or testing.
        #
        enable-os-refresh-update: false

        # Whether or not to perform OS upgrades when machines are
        # provisioned. The default option of true is recommended for use
        # in production systems, but disabling this can speed up local
        # deployments for development or testing.
        #
        enable-os-upgrade: false

