lab:
  location: intel
  racks:
  - rack: pod5
    nodes:
    - name: rack-5-m1
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: eth1
        spaces: [admin]
        mac: ["00:1E:67:CF:BB:54"]
      - ifname: eth4
        spaces: [data]
        mac: ["90:E2:BA:85:4E:2C"]
      - ifname: eth5
        spaces: [public]
        mac: ["90:E2:BA:85:4E:2D"]
      power:
        type: ipmi
        address: 10.2.117.85
        user: root
        pass: root
    - name: rack-5-m2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth1
        spaces: [admin]
        mac: ["00:1E:67:CF:B8:93"]
      - ifname: eth4
        spaces: [data]
        mac: ["90:E2:BA:84:08:B8"]
      - ifname: eth5
        spaces: [public]
        mac: ["90:E2:BA:84:08:B9"]
      power:
        type: ipmi
        address: 10.2.117.86
        user: root
        pass: root
    - name: rack-5-m3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth1
        spaces: [admin]
        mac: ["00:1E:67:E0:08:7F"]
      - ifname: eth4
        spaces: [data]
        mac: ["90:E2:BA:84:07:0D"]
      - ifname: eth5
        spaces: [public]
        mac: ["90:E2:BA:84:07:0E"]
      power:
        type: ipmi
        address: 10.2.117.87
        user: root
        pass: root
    - name: rack-5-m4
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: eth1
        spaces: [admin]
        mac: ["00:1E:67:E0:08:B1"]
      - ifname: eth4
        spaces: [data]
        mac: ["90:E2:BA:83:FD:80"]
      - ifname: eth5
        spaces: [public]
        mac: ["90:E2:BA:83:FD:81"]
      power:
        type: ipmi
        address: 10.2.117.88
        user: root
        pass: root
    - name: rack-5-m5
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: eth1
        spaces: [admin]
        mac: ["00:1E:67:E0:0A:4B"]
      - ifname: eth4
        spaces: [data]
        mac: ["90:E2:BA:75:22:74"]
      - ifname: eth5
        spaces: [public]
        mac: ["90:E2:BA:75:22:75"]
      power:
        type: ipmi
        address: 10.2.117.89
        user: root
        pass: root
#    - name: rack-5-m6
#      architecture: x86_64
#      roles: [compute,storage]
#      nics:
#      - ifname: eth1
#        spaces: [admin]
#        mac: ["98:4F:EE:10:03:43"]
#      - ifname: eth4
#        spaces: [data]
#        mac: ["00:1E:67:9C:3E:54"]
#      - ifname: eth5
#        spaces: [public]
#        mac: ["00:1E:67:9C:3E:55"]
#      power:
#        type: ipmi
#        address: 10.2.117.90
#        user: root
#        pass: root
    floating-ip-range: 10.5.15.6,10.5.15.250,10.5.15.1,10.5.15.0/24
    ext-port: "br-eth5"
    dns: 8.8.8.8
    osdomainname:
opnfv:
    release: c
    distro: trusty
    type: nonha
    openstack: liberty
    sdncontroller:
    - type: nosdn
    storage:
    - type: ceph
      disk: /dev/sdb
    feature: odl_l2
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 10.5.1.0/24
      gateway: 10.5.1.1
      vlan:
    - type: data
      bridge: brData
      cidr: 10.5.12.0/24
      gateway:
      vlan:
    - type: public
      bridge: brPublic
      cidr: 10.5.15.0/24
      gateway: 10.5.15.254
      vlan:
    - type: external
      bridge: brExt
      cidr:
      gateway:
      ipaddress: 10.2.117.92
      vlan:
