lab:
  location: intel
  racks:
  - rack: pod9
    nodes:
    - name: rack-9-m1
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: eth3
        spaces: [admin]
        mac: ["00:1E:67:D4:30:38"]
      - ifname: eth0
        spaces: [data]
        mac: ["00:1E:67:C5:5B:08"]
      - ifname: eth1
        spaces: [public]
        mac: ["00:1E:67:C5:5B:09"]
      power:
        type: ipmi
        address: 10.2.117.142
        user: root
        pass: root
    - name: rack-9-m2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth3
        spaces: [admin]
        mac: ["00:1E:67:D4:33:A2"]
      - ifname: eth0
        spaces: [data]
        mac: ["00:1E:67:E2:6C:74"]
      - ifname: eth1
        spaces: [public]
        mac: ["00:1E:67:E2:6C:75"]
      power:
        type: ipmi
        address: 10.2.117.144
        user: root
        pass: root
    - name: rack-9-m3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth3
        spaces: [admin]
        mac: ["00:1E:67:D4:2F:BA"]
      - ifname: eth0
        spaces: [data]
        mac: ["00:1E:67:C5:5B:00"]
      - ifname: eth1
        spaces: [public]
        mac: ["00:1E:67:C5:5B:01"]
      power:
        type: ipmi
        address: 10.2.117.146
        user: root
        pass: root
    floating-ip-range: 10.9.15.6,10.9.15.250,10.9.15.254,10.9.15.0/24
    ext-port: "00:1E:67:C5:5B:09"
    dns: 8.8.8.8
    osdomainname:
opnfv:
    release: c
    distro: trusty
    type: nonha
    openstack: mitaka
    sdncontroller:
    - type: nosdn
    storage:
    - type: ceph
      disk: /srv
    feature: odl_l2
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 10.9.1.0/24
      gateway: 10.9.1.1
      vlan: 901
    - type: data
      bridge: brData
      cidr: 10.9.12.0/24
      gateway:
      vlan: 902
    - type: public
      bridge: brPublic
      cidr: 10.9.15.0/24
      gateway: 10.9.15.254
      vlan: 905
    - type: external
      bridge: brExt
      cidr:
      gateway:
      ipaddress: 10.2.117.143
      vlan:
