labconfig:
    lab_location: intelpod9
    bridges:
        - type: admin
          bridge: brAdm
          cidr: 10.9.1.0/24
          gateway: 10.9.1.1
        - type: data
          bridge: brData
          cidr: 10.9.12.0/24
          gateway:
        - type: public
          bridge: brPublic
          cidr: 10.9.15.0/24
          gateway: 10.9.15.254
        - type: external
          bridge: brExt
          cidr:
          gateway:
          ipaddress: 10.2.117.143
    labsettings:
        upstream_dns: 8.8.8.8
    nodes:
        - type: control
          architecture: x86_64 
          pxe_mac_address:
              - "00:1E:67:D4:30:38"
          power:
              type: ipmi
              address: 10.2.117.142
              user: root
              pass: root
        - type: compute
          architecture: x86_64 
          pxe_mac_address:
              - "00:1E:67:D4:33:A3"
          power:
              type: ipmi
              address: 10.2.117.144
              user: root
              pass: root
        - type: compute
          architecture: x86_64 
          pxe_mac_address:
              - "00:1E:67:D4:2F:BA"
          power:
              type: ipmi
              address: 10.2.117.146
              user: root
              pass: root
opnfv:
    release: c
    distro: trusty
    type: nonha
    openstack: liberty
    sdncontroller: 
        - type: nosdn
    storage: 
        - type: ceph
          disk: sda,sdb
    floating-ip-range: 
    feature: odl_l2 
    ext-port: eth0
