opnfv-{{ lab.location }}{{ lab.racks[0].rack }}-maas:
opnfv:
{% if opnfv.spaces_dict.osapi is defined %}
{% set net_prefix = opnfv.spaces_dict.osapi.cidr[:-4] %}
{% else %}
{% set net_prefix = opnfv.spaces_dict.admin.cidr[:-4] %}
{% endif %}
  admNetgway: {{ opnfv.spaces_dict.admin.gateway }}
  admNetwork: {{ net_prefix }}2
  admin_password: openstack
  ip_address: {{ os.brAdmIP }}
  maas_name: {{ lab.location }}{{ lab.racks[0].rack }}
  main_archive: http://archive.ubuntu.com/ubuntu
  upstream_dns: {{ lab.racks[0].dns }}
{% if opnfv.storage_dict.ceph is defined %}
  ceph-disk: {{ opnfv.storage_dict.ceph.disk }}
{% endif %}
{% if opnfv.spaces_dict.data is defined %}
{% set netdata_prefix = opnfv.spaces_dict.data.cidr[:-4] %}
  dataNetwork: {{ opnfv.spaces_dict.data.cidr }}
{% endif %}
  ext-port: {{ lab.racks[0]['ext-port'] }}
  ext_port: {{ lab.racks[0]['ext-port'] }}
  floating-ip-range: {{ lab.racks[0]['floating-ip-range'] }}
  interface-enable: {{ lab.racks[0].ifnamelist }}
{% if opnfv.spaces_dict.public is defined %}
{% set netpublic_prefix = opnfv.spaces_dict.public.cidr[:-4] %}
  publicNetwork: {{ opnfv.spaces_dict.public.cidr }}
{% endif %}
  spaces:
{% for net in opnfv.spaces %}
  - bridge: {{ net.bridge }}
    cidr: {{ net.cidr }}
    gateway: {{ net.gateway or '' }}
    type: {{ net.type }}
    vlan: {{ net.vlan or '' }}
{% endfor %}
  storage:
{% for storage in opnfv.storage %}
  - disk: {{ storage.disk }}
    type: {{ storage.type }}
{% endfor %}
{% if opnfv.spaces_dict.storage is defined %}
  storageNetwork: {{ opnfv.spaces_dict.storage.cidr }}
{% endif %}
  units: {{ lab.racks[0].nodes|count }}
  vip:
{% if opnfv.spaces_dict.public is defined %}
    dashboard: {{ netpublic_prefix }}21 {{ net_prefix }}21
    glance: {{ netpublic_prefix }}22 {{ net_prefix }}22
    keystone: {{ netpublic_prefix }}23 {{ net_prefix }}23
    ceilometer: {{ netpublic_prefix }}24 {{ net_prefix }}24
    mysql: {{ net_prefix }}25
    nova: {{ netpublic_prefix }}26 {{ net_prefix }}26
    neutron: {{ netpublic_prefix }}27 {{ net_prefix }}27
    heat: {{ netpublic_prefix }}28 {{ net_prefix }}28
    cinder: {{ netpublic_prefix }}29 {{ net_prefix }}29
    radosgw: {{ netpublic_prefix }}30 {{ net_prefix }}30
{% else %}
    dashboard: {{ net_prefix }}21
    glance: {{ net_prefix }}22
    keystone: {{ net_prefix }}23
    ceilometer: {{ net_prefix }}24
    mysql: {{ net_prefix }}25
    nova: {{ net_prefix }}26
    neutron: {{ net_prefix }}27
    heat: {{ net_prefix }}28
    cinder: {{ net_prefix }}29
    radosgw: {{ net_prefix }}30
{% endif %}
