labconfig:
    lab_location: orangepod1
    bridges:
        - type: admin
          bridge: brAdm
          cidr: 192.168.2.0/24
          gateway: 192.168.2.1
        - type: data
          bridge: brData
          cidr: 192.168.12.0/24
          gateway:
        - type: storage
          bridge: brStorage
          cidr: 192.168.22.0/24
          gateway:
    labsettings:
        upstream_dns: 192.168.2.1
    nodes:
        - type: compute
          architecture: x86_64
          pxe_mac_address:
              - "38:63:bb:3f:bc:c8"
          power:
              type: ipmi
              address: 192.168.2.11
              user: Administrator
              pass: pod2Admin
        - type: compute
          architecture: x86_64
          pxe_mac_address:
              - "38:63:bb:44:34:84"
          power:
              type: ipmi
              address: 192.168.2.12
              user: Administrator
              pass: po2Admin
        - type: compute
          architecture: x86_64
          pxe_mac_address:
              - "38:63:bb:3f:1d:8c"
          power:
              type: ipmi
              address: 192.168.2.13
              user: Administrator
              pass: pod2Admin
        - type: compute
          architecture: x86_64
          pxe_mac_address:
              - "38:63:bb:3f:2d:a8"
          power:
              type: ipmi
              address: 192.168.2.14
              user: Administrator
              pass: pod2Admin
        - type: control
          architecture: x86_64
          pxe_mac_address:
              - "94:57:a5:52:c9:48"
          power:
              type: ipmi
              address: 192.168.2.15
              user: Administrator
              pass: pod2Admin
        - type: control
          architecture: x86_64
          pxe_mac_address:
              - "94:57:a5:52:63:b0"
          power:
              type: ipmi
              address: 192.168.2.16
              user: Administrator
              pass: pod2Admin
        - type: control
          architecture: x86_64
          pxe_mac_address:
              - "94:57:a5:52:f1:80"
          power:
              type: ipmi
              address: 192.168.2.17
              user: Administrator
              pass: pod2Admin

opnfv:
    release: c
    distro: trusty
    type: nonha
    openstack: liberty
    sdncontroller:
        - type: nosdn
    storage:
        - type: ceph
          disk: /srv/osd
    floating-ip-range:
    feature: odl_l2
    ext-port: eth5
