lab:
  location: orange
  racks:
  - rack: pod2
    nodes:
    - name: rack-2-m1
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["38:63:bb:3f:1d:8c"]
      - ifname: ens3f0.2056
        spaces: [public]
        mac: ["a0:36:9f:4e:88:38"]
      - ifname: ens3f0
        spaces: [floating]
        mac: ["a0:36:9f:4e:88:38"]
      - ifname: ens3f1
        spaces: [data]
        mac: ["a0:36:9f:4e:88:3a"]
      power:
        type: ipmi
        address: 10.0.0.16
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m2
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["38:63:bb:44:34:84"]
      - ifname: ens3f0.2056
        spaces: [public]
        mac: ["a0:36:9f:4e:8b:0c"]
      - ifname: ens3f0
        spaces: [floating]
        mac: ["a0:36:9f:4e:8b:0c"]
      - ifname: ens3f1
        spaces: [data]
        mac: ["a0:36:9f:4e:8b:0e"]
      power:
        type: ipmi
        address: 10.0.0.17
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m3
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["38:63:bb:3f:bc:c8"]
      - ifname: ens3f0.2056
        spaces: [public]
        mac: ["a0:36:9f:4e:88:5c"]
      - ifname: ens3f0
        spaces: [floating]
        mac: ["a0:36:9f:4e:88:5c"]
      - ifname: ens3f1
        spaces: [data]
        mac: ["a0:36:9f:4e:88:5e"]
      power:
        type: ipmi
        address: 10.0.0.18
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m4
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["1c:98:ec:1c:5d:88"]
      - ifname: ens3f0.2056
        spaces: [public]
        mac: ["a0:36:9f:1f:67:1c"]
      - ifname: ens3f0
        spaces: [floating]
        mac: ["a0:36:9f:1f:67:1c"]
      - ifname: ens3f1
        spaces: [data]
        mac: ["a0:36:9f:1f:67:1e"]
      power:
        type: ipmi
        address: 10.0.0.29
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m5
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["1c:98:ec:1d:84:7c"]
      - ifname: ens3f0.2056
        spaces: [public]
        mac: ["a0:36:9f:1f:66:a4"]
      - ifname: ens3f0
        spaces: [floating]
        mac: ["a0:36:9f:1f:66:a4"]
      - ifname: ens3f1
        spaces: [data]
        mac: ["a0:36:9f:1f:66:a6"]
      power:
        type: ipmi
        address: 10.0.0.30
        user: Administrator
        pass: opnfv2017
    floating-ip-range: 161.105.231.4,161.105.231.62,161.105.231.1,161.105.231.0/26
    ext-port: "ens3f0"
    dns: 10.2.0.1
    osdomainname:
opnfv:
    release: c
    distro: xenial
    type: nonha
    openstack: newton
    sdncontroller:
    - type: nosdn
    storage:
    - type: ceph
      disk: /dev/sdb
    feature: odl_l2
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 10.2.0.0/24
      gateway: 10.2.0.1
      vlan:
    - type: data
      bridge: brData
      cidr: 10.2.3.0/24
      gateway:
      vlan:
    - type: public
      bridge: brApi
      cidr: 10.2.1.0/24
      gateway:
      vlan:
    - type: floating
      bridge: brFloating
      cidr:
      gateway:
      vlan:
