lab:
  location: orange
  racks:
  - rack: pod2
    nodes:
    - name: rack-2-m1
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["1c:98:ec:11:ad:08"]
      - ifname: eno2.2056
        rename: eno99.2056
        spaces: [public]
        mac: ["1c:98:ec:11:ad:09"]
      - ifname: eno2
        rename: eno99
        spaces: [floating]
        mac: ["1c:98:ec:11:ad:09"]
      - ifname: eno3
        spaces: [data]
        mac: ["1c:98:ec:11:ad:0a"]
      power:
        type: ipmi
        address: 10.0.0.22
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m2
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["1c:98:ec:11:c2:c4"]
      - ifname: eno2.2056
        rename: eno99.2056
        spaces: [public]
        mac: ["1c:98:ec:11:c2:c5"]
      - ifname: eno2
        rename: eno99
        spaces: [floating]
        mac: ["1c:98:ec:11:c2:c5"]
      - ifname: eno3
        spaces: [data]
        mac: ["1c:98:ec:11:c2:c6"]
      power:
        type: ipmi
        address: 10.0.0.23
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m3
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["1c:98:ec:11:9d:c4"]
      - ifname: eno2.2056
        rename: eno99.2056
        spaces: [public]
        mac: ["1c:98:ec:11:9c:c5"]
      - ifname: eno2
        rename: eno99
        spaces: [floating]
        mac: ["1c:98:ec:11:9c:c5"]
      - ifname: eno3
        spaces: [data]
        mac: ["1c:98:ec:11:9c:c6"]
      power:
        type: ipmi
        address: 10.0.0.24
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m4
      architecture: x86_64
      roles: [compute]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["1c:98:ec:1c:5d:88"]
      - ifname: ens3f0.2056
        rename: eno99.2056
        spaces: [public]
        mac: ["a0:36:9f:1f:67:1c"]
      - ifname: ens3f0
        rename: eno99
        spaces: [floating]
        mac: ["a0:36:9f:1f:67:1c"]
      - ifname: ens3f1
        spaces: [data]
        mac: ["a0:36:9f:1f:67:1e"]
      power:
        type: ipmi
        address: 10.0.0.29
        user: Administrator
        pass: opnfv2017
    - name: rack-2-m5
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: eno1
        spaces: [admin]
        mac: ["1c:98:ec:1d:84:7c"]
      - ifname: ens3f0.2056
        rename: eno99.2056
        spaces: [public]
        mac: ["a0:36:9f:1f:66:a4"]
      - ifname: ens3f0
        rename: eno99
        spaces: [floating]
        mac: ["a0:36:9f:1f:66:a4"]
      - ifname: ens3f1
        spaces: [data]
        mac: ["a0:36:9f:1f:66:a6"]
      power:
        type: ipmi
        address: 10.0.0.30
        user: Administrator
        pass: opnfv2017
    floating-ip-range: 161.105.231.4,161.105.231.62,161.105.231.1,161.105.231.0/26
    ext-port: "eno99"
    dns: 10.2.0.1
    osdomainname:
opnfv:
    release: c
    distro: xenial
    type: noha
    openstack: newton
    sdncontroller:
    - type: nosdn
    storage:
    - type: ceph
      disk: /dev/sdb /deb/sdc
    feature: odl_l2
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 10.2.0.0/24
      gateway: 10.2.0.1
      vlan:
    - type: data
      bridge: brData
      cidr: 10.2.3.0/24
      gateway:
      vlan:
    - type: public
      bridge: brApi
      cidr: 10.2.1.0/24
      gateway: 10.2.1.1
      vlan: 2056
    - type: floating
      bridge: brFloating
      cidr:
      gateway:
      vlan:
