lab:
  location: orange
  racks:
  - rack: pod1
    nodes:
    - name: rack-1-m1
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["68:b5:99:74:e3:a8"]
      - ifname: eth2
        spaces: [data]
        mac: ["68:b5:99:74:e3:ae"]
      - ifname: eth3
        spaces: [storage]
        mac: ["68:b5:99:74:e3:ac"]
      power:
        type: ipmi
        address: 192.168.1.11
        user: Administrator
        pass: pod2Admin
    - name: rack-1-m2
      architecture: x86_64
      roles: [control,network]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["68:b5:99:75:05:5e"]
      - ifname: eth2
        spaces: [data]
        mac: ["68:b5:99:75:05:64"]
      - ifname: eth3
        spaces: [storage]
        mac: ["68:b5:99:75:05:62"]
      power:
        type: ipmi
        address: 192.168.1.12
        user: Administrator
        pass: pod2Admin:
    - name: rack-1-m3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["94:57:a5:52:53:7c"]
      - ifname: eth3
        spaces: [data]
        mac: ["94:57:a5:52:53:7f"]
      - ifname: eth2
        spaces: [storage]
        mac: ["94:57:a5:52:53:7e"]
      power:
        type: ipmi
        address: 192.168.1.13
        user: Administrator
        pass: pod2Admin
    - name: rack-1-m4
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["94:57:a5:52:c1:54"]
      - ifname: eth3
        spaces: [data]
        mac: ["94:57:a5:52:c1:57"]
      - ifname: eth2
        spaces: [storage]
        mac: ["94:57:a5:52:c1:56"]
      power:
        type: ipmi
        address: 192.168.1.14
        user: Administrator
        pass: pod2Admin
    - name: rack-1-m5
      architecture: x86_64
      roles: [network]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["94:57:a5:52:c1:d8"]
      - ifname: eth3
        spaces: [data]
        mac: ["94:57:a5:52:c1:db"]
      - ifname: eth2
        spaces: [storage]
        mac: ["94:57:a5:52:c1:da"]
      power:
        type: ipmi
        address: 192.168.1.15
        user: Administrator
        pass: pod2Admin
    floating-ip-range: 161.105.231.2,161.105.231.62,161.105.231.1,161.105.231.0/26
    ext-port: "68:b5:99:75:05:60"
    dns: 192.168.1.1
opnfv:
  release: c
  distro: trusty
  type: nonha
  openstack: liberty
  sdncontroller:
  - type: nosdn
  storage:
  - type: ceph
    disk: /dev/sdb /dev/sdc
  feature: odl_l2
  spaces:
  - type: admin
    bridge: brAdm
    cidr: 192.168.1.0/24
    gateway: 192.168.1.1
    vlan:
  - type: data
    bridge: brData
    cidr: 192.168.11.0/24
    gateway:
    vlan:
  - type: storage
    bridge: brStorage
    cidr: 192.168.21.0/24
    gateway:
