lab:
  location: intel
  racks:
  - rack: pod19
    nodes:
    - name: rack-19-m1
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["a4:bf:01:4b:55:f5"]
      - ifname: intf1
        spaces: [data]
        mac: ["3c:fd:fe:aa:b8:f4"]
      - ifname: intf3
        spaces: [floating]
        mac: ["a4:bf:01:4b:55:f4"]
#      - ifname: intf2.1193
#        spaces: [public]
#        mac: ["3c:fd:fe:aa:b8:f5"]
      - ifname: intf2
        spaces: [storage]
        mac: ["3c:fd:fe:aa:b8:f5"]
      power:
        type: ipmi
        address: 10.10.190.11
        user: root
        pass: root
    - name: rack-19-m2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["a4:bf:01:4b:4f:9d"]
      - ifname: intf1
        spaces: [data]
        mac: ["3c:fd:fe:aa:b7:fc"]
      - ifname: intf3
        spaces: [floating]
        mac: ["a4:bf:01:4b:4f:9c"]
#      - ifname: intf2.1193
#        spaces: [public]
#        mac: ["3c:fd:fe:aa:b7:fd"]
      - ifname: intf2
        spaces: [storage]
        mac: ["3c:fd:fe:aa:b7:fd"]
      power:
        type: ipmi
        address: 10.10.190.12
        user: root
        pass: root
    - name: rack-19-m3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["a4:bf:01:4b:4f:5e"]
      - ifname: intf1
        spaces: [data]
        mac: ["3c:fd:fe:aa:bd:d4"]
      - ifname: intf3
        spaces: [floating]
        mac: ["a4:bf:01:4b:4f:5d"]
#      - ifname: intf2.1193
#        spaces: [public]
#        mac: ["3c:fd:fe:aa:bd:d5"]
      - ifname: intf2
        spaces: [storage]
        mac: ["3c:fd:fe:aa:bd:d5"]
      power:
        type: ipmi
        address: 10.10.190.13
        user: root
        pass: root
    - name: rack-19-m4
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["a4:bf:01:4b:4d:2e"]
      - ifname: intf1
        spaces: [data]
        mac: ["3c:fd:fe:aa:b9:c8"]
      - ifname: intf3
        spaces: [floating]
        mac: ["a4:bf:01:4b:4d:2d"]
#      - ifname: intf2.1193
#        spaces: [public]
#        mac: ["3c:fd:fe:aa:b9:c9"]
      - ifname: intf2
        spaces: [storage]
        mac: ["3c:fd:fe:aa:b9:c9"]
      power:
        type: ipmi
        address: 10.10.190.14
        user: root
        pass: root
    - name: rack-19-m5
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["a4:bf:01:4b:56:11"]
      - ifname: intf1
        spaces: [data]
        mac: ["3c:fd:fe:aa:ba:38"]
      - ifname: intf3
        spaces: [floating]
        mac: ["a4:bf:01:4b:56:10"]
#      - ifname: intf2.1193
#        spaces: [public]
#        mac: ["3c:fd:fe:aa:ba:39"]
      - ifname: intf2
        spaces: [storage]
        mac: ["3c:fd:fe:aa:ba:39"]
      power:
        type: ipmi
        address: 10.10.190.15
        user: root
        pass: root
    floating-ip-range: 10.10.190.40,10.10.190.250,10.10.190.1,10.10.190.0/24
    ext-port: "intf3"
    dns: 8.8.8.8
    osdomainname:
opnfv:
    release: d
    distro: xenial
    type: noha
    openstack: pike
    sdncontroller:
    - type: nosdn
    storage:
    - type: ceph
      disk: /srv
    feature: odl_l2
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 10.10.191.0/24
      gateway: 10.10.191.2
      vlan:
    - type: data
      cidr: 10.10.192.0/24
      gateway:
      vlan:
    - type: storage
      cidr: 10.10.193.0/24
      gateway:
      vlan:
    - type: floating
      cidr: 10.10.190.0/24
      gateway:
      vlan:
#    - type: public
#      cidr: 10.10.195.0/24
#      gateway:
#      vlan: 1193
