        auto lo
            iface lo inet loopback
{% set ethid = 0 %}
{% for net in opnfv.spaces %}

        auto eth{{ ethid }}
            iface eth{{ ethid }} inet static
            netmask 255.255.255.0
{% if net.type!='external' %}
{% set net_prefix = net.cidr[:-4] %}
            address {{ net_prefix }}5
{% else %}
            address {{ net.ipaddress }}
{% endif %}
{% if net.type=='admin' %}
            gateway {{ net.gateway }}
            dns-nameservers {{ lab.racks[0].dns }} {{ net_prefix }}5 127.0.0.1
{% endif %}
{% set ethid = ethid+1 %}
{% endfor %}
