lab:
  location: lenovo
  racks:
  - rack: pod1
    nodes:
    - name: rack-1-m1
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["24:8a:07:3f:84:ac"]
      - ifname: intf101
        spaces: [floating]
        mac: ["24:8a:07:3f:84:ad"]
      power:
        type: ipmi
        address: 192.0.5.125
        user: USERID
        pass: PASSW0RD
    - name: rack-1-m2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["24:8a:07:3f:96:86"]
      - ifname: intf101
        spaces: [floating]
        mac: ["24:8a:07:3f:96:87"]
      power:
        type: ipmi
        address: 192.0.5.126
        user: USERID
        pass: PASSW0RD
    - name: rack-1-m3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["24:8a:07:3f:84:c4"]
      - ifname: intf101
        spaces: [floating]
        mac: ["24:8a:07:3f:84:c5"]
      power:
        type: ipmi
        address: 192.0.5.127
        user: USERID
        pass: PASSW0RD
    - name: rack-1-m4
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["24:8a:07:3f:96:4e"]
      - ifname: intf101
        spaces: [floating]
        mac: ["24:8a:07:3f:96:4f"]
      power:
        type: ipmi
        address: 192.0.5.128
        user: USERID
        pass: PASSW0RD
    - name: rack-1-m5
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["24:8a:07:3f:95:fe"]
      - ifname: intf101
        spaces: [floating]
        mac: ["24:8a:07:3f:95:ff"]
      power:
        type: ipmi
        address: 192.0.5.129
        user: USERID
        pass: PASSW0RD
    floating-ip-range: 172.21.159.6,172.21.159.100,172.21.159.5,172.21.159.0/24
    ext-port: "intf101"
    dns: 8.8.8.8
    osdomainname:
opnfv:
    release: d
    distro: xenial
    type: nonha
    openstack: Newton
    sdncontroller:
    - type: nosdn
    storage:
    - type: ceph
      disk: /dev/sdb
    feature: odl_l2
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 192.0.5.0/24
      gateway: 192.0.5.5
      vlan:
    - type: floating
      bridge: brPublic
      cidr: 172.21.159.0/24
      gateway: 172.21.159.1
      vlan:
    - type: external
      bridge: brExt
      cidr:
      gateway: 10.240.71.1
      ipaddress: 10.240.71.213
      vlan:
