lab:
  location: juniper
  racks:
  - rack: pod1
    nodes:
    - name: rack-R4N3B1-m1
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["0c:c4:7a:53:57:c2"]
      - ifname: intf101
        spaces: [floating]
        mac: ["0c:c4:7a:53:57:c3"]
      power:
        type: ipmi
        address: 10.10.7.84
        user: ADMIN
        pass: ADMIN
    - name: rack-R4N4B2-m2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["0c:c4:7a:16:2a:70"]
      - ifname: intf101
        spaces: [floating]
        mac: ["0c:c4:7a:16:2a:71"]
      power:
        type: ipmi
        address: 10.10.7.92
        user: ADMIN
        pass: ADMIN
    - name: rack-R4N4B3-m3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["0c:c4:7a:16:2a:0a"]
      - ifname: intf101
        spaces: [floating]
        mac: ["0c:c4:7a:16:2a:0b"]
      power:
        type: ipmi
        address: 10.10.7.93
        user: ADMIN
        pass: ADMIN
    - name: rack-R4N4B4-m4
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["0c:c4:7a:16:22:9c"]
      - ifname: intf101
        spaces: [floating]
        mac: ["0c:c4:7a:16:22:9d"]
      power:
        type: ipmi
        address: 10.10.7.95
        user: ADMIN
        pass: ADMIN
    - name: rack-R4N3B2-m5
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["0c:c4:7a:53:57:16"]
      - ifname: intf101
        spaces: [floating]
        mac: ["0c:c4:7a:53:57:17"]
      power:
        type: ipmi
        address: 10.10.7.85
        user: ADMIN
        pass: ADMIN
    floating-ip-range: 10.10.10.6,10.10.10.250,10.10.10.1,10.10.10.0/24
    ext-port: "intf101"
    dns: 8.8.8.8
    osdomainname:
opnfv:
    release: d
    distro: xenial
    type: ha
    openstack: ocata
    sdncontroller:
    - type: ocl
    storage:
    - type: ceph
      disk: /srv
    feature: nofeature
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 172.16.50.0/24
      gateway: 172.16.50.1
      vlan:
    - type: floating
      bridge: brPublic
      cidr: 10.10.0.0/20
      gateway:
      vlan:
