lab:
  location: cengn
  racks:
  - rack: pod1
    nodes:
    - name: rack-IRA2-SymKloudBlade1
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["00:A0:A5:90:89:66"]
      - ifname: intf101
        spaces: [floating]
        mac: ["00:A0:A5:90:89:67"]
      - ifname: intf102
        spaces: [data]
        mac: ["00:A0:A5:90:89:65"]
      power:
        type: ipmi
        address: 10.252.40.11
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["00:A0:A5:90:89:A8"]
      - ifname: intf101
        spaces: [floating]
        mac: ["00:A0:A5:90:89:A9"]
      - ifname: intf102
        spaces: [data]
        mac: ["00:A0:A5:90:89:A7"]
      power:
        type: ipmi
        address: 10.252.40.12
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["00:A0:A5:90:89:28"]
      - ifname: intf101
        spaces: [floating]
        mac: ["00:A0:A5:90:89:29"]
      - ifname: intf102
        spaces: [data]
        mac: ["00:A0:A5:90:89:27"]
      power:
        type: ipmi
        address: 10.252.40.13
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade4
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["00:A0:A5:89:30:C6"]
      - ifname: intf101
        spaces: [floating]
        mac: ["00:A0:A5:89:30:C7"]
      - ifname: intf102
        spaces: [data]
        mac: ["00:A0:A5:89:30:C5"]
      power:
        type: ipmi
        address: 10.252.40.14
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade5
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf100
        spaces: [admin]
        mac: ["00:A0:A5:90:89:94"]
      - ifname: intf101
        spaces: [floating]
        mac: ["00:A0:A5:90:89:95"]
      - ifname: intf102
        spaces: [data]
        mac: ["00:A0:A5:90:89:93"]
      power:
        type: ipmi
        address: 10.252.40.15
        user: admin
        pass: admin
    floating-ip-range: 10.252.42.6,10.252.42.249,10.252.42.254,10.252.42.0/24
    ext-port: "intf101"
    dns: 8.8.8.8
    osdomainname:
opnfv:
  release: c
  distro: xenial
  type: nonha
  openstack: mitaka
  sdncontroller:
  - type: nosdn
  storage:
  - type: ceph
    disk: /dev/sdb /dev/sdc
  feature: odl_l2
  spaces:
  - type: admin
    bridge: brAdm
    cidr: 10.252.41.0/24
    gateway: 10.252.41.254
    vlan:
  - type: floating
    bridge: brPublic
    cidr: 10.252.42.0/24
    gateway: 10.252.42.254
    vlan:
  - type: data
    bridge: brData
    cidr: 192.168.20.0/24
    gateway: 192.168.20.254
    vlan:
