lab:
  location: cengn
  racks:
  - rack: pod1
    nodes:
    - name: rack-IRA2-SymKloudBlade1
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: enp11s0
        spaces: [admin]
        mac: ["00:A0:A5:90:89:66"]
      - ifname: enp12s0
        spaces: [public]
        mac: ["00:A0:A5:90:89:67"]
      - ifname: enp3s0f1
        spaces: [data]
        mac: ["00:A0:A5:90:89:65"]
      power:
        type: ipmi
        address: 10.21.5.11
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: enp11s0
        spaces: [admin]
        mac: ["00:A0:A5:90:89:A8"]
      - ifname: enp12s0
        spaces: [public]
        mac: ["00:A0:A5:90:89:A9"]
      - ifname: enp3s0f1
        spaces: [data]
        mac: ["00:A0:A5:90:89:A7"]
      power:
        type: ipmi
        address: 10.21.5.12
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: enp11s0
        spaces: [admin]
        mac: ["00:A0:A5:90:89:28"]
      - ifname: enp12s0
        spaces: [public]
        mac: ["00:A0:A5:90:89:29"]
      - ifname: enp3s0f1
        spaces: [data]
        mac: ["00:A0:A5:90:89:27"]
      power:
        type: ipmi
        address: 10.21.5.13
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade4
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: enp11s0
        spaces: [admin]
        mac: ["00:A0:A5:89:30:C6"]
      - ifname: enp12s0
        spaces: [public]
        mac: ["00:A0:A5:89:30:C7"]
      - ifname: enp3s0f1
        spaces: [data]
        mac: ["00:A0:A5:89:30:C5"]
      power:
        type: ipmi
        address: 10.21.5.14
        user: admin
        pass: admin
    - name: rack-IRA2-SymKloudBlade5
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: enp11s0
        spaces: [admin]
        mac: ["00:A0:A5:90:89:94"]
      - ifname: enp12s0
        spaces: [public]
        mac: ["00:A0:A5:90:89:95"]
      - ifname: enp3s0f1
        spaces: [data]
        mac: ["00:A0:A5:90:89:93"]
      power:
        type: ipmi
        address: 10.21.5.15
        user: admin
        pass: admin
    floating-ip-range: 10.21.6.6,10.21.6.250,10.21.6.254,10.21.6.0/24
    ext-port: "enp12s0"
    dns: 8.8.8.8
    osdomainname:
opnfv:
  release: c
  distro: xenial
  type: nonha
  openstack: mitaka
  sdncontroller:
  - type: nosdn
  storage:
  - type: ceph
    disk: /dev/sdb /dev/sdc
  feature: odl_l2
  spaces:
  - type: admin
    bridge: brAdm
    cidr: 10.21.0.0/24
    gateway: 10.21.0.254
    vlan:
  - type: floating
    bridge: brPublic
    cidr: 10.21.6.0/24
    gateway: 10.21.6.254
    vlan:
  - type: data
    bridge: brData
    cidr: 192.168.20.0/24
    gateway: 192.168.20.1
    vlan: