lab:
  location: intel
  racks:
  - rack: pod5
    nodes:
    - name: rack-5-m1
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["00:1E:67:CF:BB:54"]
      - ifname: intf1
        spaces: [data]
        mac: ["90:E2:BA:85:4E:2C"]
      - ifname: intf3
        spaces: [floating]
        mac: ["00:1E:67:CF:BB:53"]
      - ifname: intf1.214
        spaces: [storage]
        mac: ["90:E2:BA:85:4E:2C"]
      - ifname: intf2
        spaces: [public]
        mac: ["90:E2:BA:85:4E:2D"]
      power:
        type: ipmi
        address: 10.10.210.11
        user: root
        pass: root
    - name: rack-5-m2
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["00:1E:67:CF:B8:93"]
      - ifname: intf1
        spaces: [data]
        mac: ["90:E2:BA:84:08:B8"]
      - ifname: intf3
        spaces: [floating]
        mac: ["00:1E:67:CF:B8:92"]
      - ifname: intf1.214
        spaces: [storage]
        mac: ["90:E2:BA:84:08:B8"]
      - ifname: intf2
        spaces: [public]
        mac: ["90:E2:BA:84:08:B9"]
      power:
        type: ipmi
        address: 10.10.210.12
        user: root
        pass: root
    - name: rack-5-m3
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["00:1E:67:E0:08:7F"]
      - ifname: intf1
        spaces: [data]
        mac: ["90:E2:BA:84:07:0C"]
      - ifname: intf3
        spaces: [floating]
        mac: ["00:1E:67:E0:08:7E"]
      - ifname: intf1.214
        spaces: [storage]
        mac: ["90:E2:BA:84:07:0C"]
      - ifname: intf2
        spaces: [public]
        mac: ["90:E2:BA:84:07:0D"]
      power:
        type: ipmi
        address: 10.10.210.13
        user: root
        pass: root
    - name: rack-5-m4
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["00:1E:67:E0:08:B1"]
      - ifname: intf1
        spaces: [data]
        mac: ["90:E2:BA:83:FD:80"]
      - ifname: intf3
        spaces: [floating]
        mac: ["00:1E:67:E0:08:B0"]
      - ifname: intf1.214
        spaces: [storage]
        mac: ["90:E2:BA:83:FD:80"]
      - ifname: intf2
        spaces: [public]
        mac: ["90:E2:BA:83:FD:81"]
      power:
        type: ipmi
        address: 10.10.210.14
        user: root
        pass: root
    - name: rack-5-m5
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: intf0
        spaces: [admin]
        mac: ["00:1E:67:E0:0A:4B"]
      - ifname: intf1
        spaces: [data]
        mac: ["90:E2:BA:75:22:74"]
      - ifname: intf3
        spaces: [floating]
        mac: ["00:1E:67:E0:0A:4A"]
      - ifname: intf1.214
        spaces: [storage]
        mac: ["90:E2:BA:75:22:74"]
      - ifname: intf2
        spaces: [public]
        mac: ["90:E2:BA:75:22:75"]
      power:
        type: ipmi
        address: 10.10.210.15
        user: root
        pass: root
#    - name: rack-5-m6
#      architecture: x86_64
#      roles: [compute,storage]
#      nics:
#      - ifname: intf0
#        spaces: [admin]
#        mac: ["98:4F:EE:10:03:43"]
#      - ifname: intf1
#        spaces: [data]
#        mac: ["00:1E:67:9C:3E:54"]
#      - ifname: intf2.4000
#        spaces: [public]
#        mac: ["00:1E:67:9C:3E:55"]
#      power:
#        type: ipmi
#        address: 10.10.210.90
#        user: root
#        pass: root
    floating-ip-range: 10.10.210.40,10.10.210.250,10.10.210.1,10.10.210.0/24
    ext-port: "intf3"
    dns: 8.8.8.8
    osdomainname:
opnfv:
    release: d
    distro: xenial
    type: nonha
    openstack: ocata
    sdncontroller:
    - type: nosdn
    storage:
    - type: ceph
      disk: /dev/sdb
    feature: odl_l2
    spaces:
    - type: admin
      bridge: brAdm
      cidr: 10.10.211.0/24
      gateway: 10.10.211.1
      vlan:
    - type: data
      bridge: brData
      cidr: 10.10.212.0/24
      gateway:
      vlan:
    - type: public
      bridge: brStor
      cidr: 10.10.213.0/24
      gateway:
      vlan:
    - type: floating
      bridge: brExt
      cidr: 10.10.210.0/24
      gateway:
      vlan:
    - type: storage
      bridge: brMgmt
      cidr: 10.10.214.0/24
      gateway:
      vlan: 214
