ubuntu:
    release: xenial
os:
    release: ocata
    git_repo:
        origin_git: False
        branch: ocata
    hyperconverged: True
    ha:
        mode: ha
        cluster_size: 3
    lxd: False
    region: RegionOne
    api:
        worker_multiplier: 1.0
        haproxy_timeout: 10000
    admin:
        role: admin
        name: admin
        password: openstack
    storage:
        ceph_replica: '2'
    network:
        controller: odl
        enhanced_ovs: False
        dvr: False
        ipv6: False
        l2_population: False
    beta:
        hacluster_ceph_radosgw: True
        huge_pages: False
        cpu_pin: False
        cpu_pin_set: all
    service:
        congress: False
        promise: True
        bindings: True
        openbaton: False
k8:
    feature:
        loadbalancer: False
    network:
        controller: nosdn
