ubuntu:
    release: xenial
os:
    release: mitaka
    hyperconverged: True
    ha:
        mode: ha
        cluster_size: 3
    lxd: False
    region: RegionOne
    api:
        worker_multiplier: 1.0
        haproxy_timeout: 10000
    admin:
        role: admin
        name: admin
        password: openstack
    storage:
        ceph_replica: '2'
    network:
        controller: odl
        enhanced_ovs: False
        dvr: False
        ipv6: False
        l2_population: False
    beta:
        hacluster_ceph_radosgw: False
        public_api: False
        huge_pages: False
