demo-maas:
  juju-bootstrap:
    arch: amd64
    disk_size: 120G
    interfaces:
    - bridge=brAdm,model=virtio
    memory: 4096
    name: bootstrap
    pool: default
    vcpus: 4
  maas:
    apt_http_proxy: null
    apt_sources:
    - ppa:maas/stable
    - ppa:juju/stable
    arch: amd64
    boot_source:
      keyring_filename: /usr/share/keyrings/ubuntu-cloudimage-keyring.gpg
      selections:
        1:
          arches: amd64
          labels: release
          os: ubuntu
          release: xenial
          subarches: '*'
      url: http://maas.ubuntu.com/images/ephemeral-v2/releases/
    disk_size: 160G
    interfaces:
    - bridge=brAdm,model=virtio
    ip_address: 
    memory: 4096
    name: opnfv-intelpod6
    network_config: 
    node_group_ifaces:
    - broadcast_ip: 
      dynamic_range:
        high: 
        low: 
      static_range:
        high: 
        low: 
    - broadcast_ip: 
      dynamic_range:
        high: 
        low: 
      static_range:
        high: 
        low: 
    - broadcast_ip: 
      dynamic_range:
        high: 
        low: 
      static_range:
        high: 
        low: 
    nodes:
    - architecture: 
      mac_addresses:
      - 
      power:
        address: 
    - architecture: 
      mac_addresses:
      - 
      power:
        address: 
    - architecture: 
      mac_addresses:
      - 
      power:
        address: 
    - architecture: 
      mac_addresses:
      - 
      power:
        address: 
    - architecture: 
      mac_addresses:
      - 
      power:
        address: 
    password: ubuntu
    pool: default
    release: trusty
    settings:
      maas_name: 
      main_archive: http://us.archive.ubuntu.com/ubuntu
      upstream_dns: 
    user: ubuntu
    vcpus: 4
    virsh:
      rsa_priv_key: /home/ubuntu/.ssh/id_rsa
      rsa_pub_key: /home/ubuntu/.ssh/id_rsa.pub
      uri: 
