labconfig:
    lab_location: intelpod6
    bridges:
        - type: admin
          bridge: brAdm
          cidr: 10.6.1.0/24
          gateway: 10.6.1.1
        - type: data
          bridge: brData
          cidr: 10.6.12.0/24
          gateway:
        - type: public
          bridge: brPublic
          cidr: 10.6.15.0/24
          gateway: 10.6.15.254
        - type: external
          bridge: brExt
          cidr:
          gateway:
          ipaddress: 10.2.117.107
    labsettings:
        upstream_dns: 8.8.8.8
    nodes:
        - type: control
          architecture: x86_64 
          pxe_mac_address:
              - "00:1e:67:d8:ba:46"
          power:
              type: ipmi
              address: 10.2.117.96
              user: root
              pass: root
        - type: control
          architecture: x86_64 
          pxe_mac_address:
              - "00:1e:67:e0:0b:72"
          power:
              type: ipmi
              address: 10.2.117.97
              user: root
              pass: root
        - type: control
          architecture: x86_64 
          pxe_mac_address:
              - "00:1e:67:e0:09:33"
          power:
              type: ipmi
              address: 10.2.117.98
              user: root
              pass: root
        - type: compute
          architecture: x86_64 
          pxe_mac_address:
              - "00:1e:67:e0:09:fb"
          power:
              type: ipmi
              address: 10.2.117.99
              user: root
              pass: root
        - type: compute
          architecture: x86_64 
          pxe_mac_address:
              - "00:1e:67:cf:bc:f8"
          power:
              type: ipmi
              address: 10.2.117.100
              user: root
              pass: root
opnfv:
    release: c
    distro: trusty
    type: nonha
    openstack: liberty
    sdncontroller: 
        - type: nosdn
    storage: 
        - type: ceph
          disk: sda,sdb
    floating-ip-range: 
    feature: odl_l2 
    ext-port: eth0
